version: '3.9' # optional since v1.27.0
services:
  docker-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./src:/frontend/src

  docker-backend:
    build:
      context: json-server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./json-server:/backend